chore(TDI-48973): Fix Sonar NoClassDefFoundError
Talend/component-runtime pull request #662
Opened 2022-12-01 15:56 UTC by fdesiles

### Requirements

* Any code change adding any logic **MUST** be tested through a unit test executed with the default build
* Any API addition **MUST** be done with a documentation update if relevant 

### Why this PR is needed?
Sonar checks fail with "java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl"

### What does this PR adds (design/code thoughts)?
https://jira.talendforge.org/browse/TDI-48973

Following SFT bump of Sonar in 9.6, builds are failing with:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl

This is linked to a bug on 9.6 using Sonar cache.

It is fixed in 9.7.1, however there is another blocker for SFT to stay on version 9.6 for the time being.

2022-12-01 16:39 UTC, acatoire reviewed
LGTM

2022-12-01 16:44 UTC, acatoire requested changes

2022-12-01 16:44 UTC, acatoire commented on Jenkinsfile
> +                            // TODO Disabling Sonar cache due to "ClassNotFoundException: com.google.common.collect.LinkedListMultimap" issue
```suggestion
                            // TODO: TDI-48980 Disabling Sonar cache due to "ClassNotFoundException: com.google.common.collect.LinkedListMultimap" issue
```

2022-12-02 08:48 UTC, acatoire approved these changes
LGTM

2022-12-02 08:50 UTC, undx approved these changes

2022-12-02 08:59 UTC, merged