feat： changelog for Release 1.60.0
Talend/component-runtime pull request #781
Opened 2023-08-16 03:07 UTC by yyin-talend

### Requirements

* Any code change adding any logic **MUST** be tested through a unit test executed with the default build
* Any API addition **MUST** be done with a documentation update if relevant 

### Why this PR is needed?

### What does this PR adds (design/code thoughts)?

2023-08-16 12:59 UTC, acatoire requested changes

2023-08-17 03:05 UTC, lxia-talend approved these changes
LGTM

2023-08-17 03:23 UTC, yyin-talend commented on documentation/src/main/antora/modules/ROOT/pages/_partials/generated_changelog.adoc
> +
ADDED

2023-08-17 07:22 UTC, acatoire approved these changes

2023-08-17 07:23 UTC, merged